import { ResumeProfile } from "@/schemas/resume";
import { TailoredResume } from "@/schemas/tailored";

export interface ConsistencyReport {
  isValid: boolean;
  errors: string[];
  warnings: string[];
  hallucinatedCompanies: string[];
  hallucinatedBullets: string[];
}

/**
 * Normalizes a string for loose, case-insensitive, whitespace-agnostic comparison.
 */
function normalizeForComparison(str: string): string {
  return str.toLowerCase().replace(/[^a-z0-9]/g, "");
}

/**
 * Server-side audit engine that validates the structural consistency between
 * the original resume profile and the tailored resume generated by the LLM.
 * Prevents fabrications, hallucinated employers, and unauthorized bullet additions.
 */
export function checkTailoringConsistency(
  original: ResumeProfile,
  tailored: TailoredResume
): ConsistencyReport {
  const errors: string[] = [];
  const warnings: string[] = [];
  const hallucinatedCompanies: string[] = [];
  const hallucinatedBullets: string[] = [];

  const originalExperiences = original.experience || [];
  const tailoredExperiences = tailored.tailoredExperience || [];

  // 1. Audit Experience Entries (Employers/Companies & Titles)
  for (const tailoredExp of tailoredExperiences) {
    const tailoredCompanyNorm = normalizeForComparison(tailoredExp.company);
    const tailoredTitleNorm = normalizeForComparison(tailoredExp.title);

    // Try to find matching original experience
    const match = originalExperiences.find((origExp) => {
      const origCompanyNorm = normalizeForComparison(origExp.company);
      // Allow matching if company matches, or both match
      return origCompanyNorm === tailoredCompanyNorm;
    });

    if (!match) {
      errors.push(`Invented Employer Found: Tailored resume contains employer "${tailoredExp.company}" which does not exist in your original profile.`);
      hallucinatedCompanies.push(tailoredExp.company);
      continue;
    }

    // Double check title change warning (which is allowed but should be recorded as a warning if drastically different)
    const titleMatch = originalExperiences.find((origExp) => {
      const origCompanyNorm = normalizeForComparison(origExp.company);
      const origTitleNorm = normalizeForComparison(origExp.title);
      return origCompanyNorm === tailoredCompanyNorm && origTitleNorm === tailoredTitleNorm;
    });

    if (!titleMatch) {
      warnings.push(`Title Adjustment: Experience at "${tailoredExp.company}" had title modified from "${match.title}" to "${tailoredExp.title}".`);
    }

    // 2. Audit experience bullets inside this entry
    const originalBullets = match.bullets || [];
    const originalBulletsNorm = originalBullets.map(normalizeForComparison);

    for (const tailoredBullet of tailoredExp.bullets || []) {
      const origBulletNorm = normalizeForComparison(tailoredBullet.original);

      // Verify that bullet.original existed in the original experience
      const existsInOriginal = originalBulletsNorm.includes(origBulletNorm);
      if (!existsInOriginal) {
        errors.push(`Unsanctioned Bullet Point: Tailored experience at "${tailoredExp.company}" refers to an original bullet point that is missing or fabricated.`);
        hallucinatedBullets.push(tailoredBullet.original);
      }

      // Check for low-confidence warnings
      if (tailoredBullet.confidence === "low") {
        warnings.push(`Low-Confidence Update: Tailoring at "${tailoredExp.company}" has low AI confidence. Reason: ${tailoredBullet.changeReason}`);
      }

      // Check for risk flags
      if (tailoredBullet.riskFlag) {
        warnings.push(`Accuracy Risk Warning: Bullet at "${tailoredExp.company}" flagged for risk: ${tailoredBullet.riskFlag}`);
      }
    }
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
    hallucinatedCompanies,
    hallucinatedBullets,
  };
}
